version: '0.1'

services:
  toolbench:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: toolbench
    volumes:
      - /public:/public
    environment:
      - CUDA_VISIBLE_DEVICES=0
    ports:
      - "7860:7860"
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: "all"
            capabilities: [gpu]
    restart: unless-stopped
